---
sidebar: sidebar 
permalink: custom-architectures-inventory-map-services-to-file-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Geben Sie an, welche Dateiknoten jeden BeeGFS-Dienst mit der Datei Inventory.yml ausführen können. 
---
= Zuordnen von BeeGFS-Services zu Datei-Nodes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Geben Sie an, welche Datei-Nodes jeden BeeGFS-Dienst mit dem ausführen können `inventory.yml` Datei:



== Überblick

In diesem Abschnitt wird die Erstellung des erläutert `inventory.yml` Datei: Dazu gehören alle Block-Nodes und die Angabe, welche Datei-Nodes jeden BeeGFS-Service ausführen können.



== Schritte

Erstellen Sie die Datei `inventory.yml` Und füllen Sie es wie folgt aus:

. Erstellen Sie oben in der Datei die Ansible-Standardinventarstruktur:
+
[source, yaml]
----
# BeeGFS HA (High_Availability) cluster inventory.
all:
  children:
----
. Erstellen Sie eine Gruppe mit allen Block-Nodes, die an diesem HA-Cluster teilnehmen:
+
[source, yaml]
----
    # Ansible group representing all block nodes:
    eseries_storage_systems:
      hosts:
        <BLOCK NODE HOSTNAME>:
        <BLOCK NODE HOSTNAME>:
        # Additional block nodes as needed.
----
. Erstellen Sie eine Gruppe, die alle BeeGFS-Dienste im Cluster und die Datei-Nodes enthält, auf denen sie ausgeführt werden:
+
[source, yaml]
----
    # Ansible group representing all file nodes:
    ha_cluster:
      children:
----
. Definieren Sie für jeden BeeGFS-Service im Cluster die bevorzugten und sekundären Dateiknoten, die diesen Service ausführen sollen:
+
[source, yaml]
----
        <SERVICE>: # Ex. "mgmt", "meta_01", or "stor_01".
          hosts:
            <FILE NODE HOSTNAME>:
            <FILE NODE HOSTNAME>:
            # Additional file nodes as needed.
----


Klicken Sie Auf link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/inventory.yml["Hier"^] Beispiel für eine komplette Bestandsdatei.
