---
sidebar: sidebar 
permalink: custom-architectures-inventory-beegfs-management.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'BeeGFS-Dienste werden mit Gruppenvariablen (Group_vars) konfiguriert.' 
---
= Definieren Sie den BeeGFS-Managementdienst
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BeeGFS-Dienste werden mit Gruppenvariablen (Group_vars) konfiguriert.



== Überblick

In diesem Abschnitt wird die Definition des BeeGFS-Managementservice erläutert. In den HA-Clustern für ein bestimmtes Dateisystem sollte nur ein Service dieses Typs vorhanden sein. Die Konfiguration dieses Services umfasst die folgenden Punkte:

* Der Servicetyp (Management).
* Definieren von Konfigurationen, die nur für diesen BeeGFS-Dienst gelten sollen.
* Konfiguration einer oder mehrerer fließender IPs (logische Schnittstellen), an denen dieser Service erreicht werden kann.
* Geben Sie an, wo/wie ein Volume Daten für diesen Service speichern soll (das BeeGFS-Managementziel).




== Schritte

Erstellen Sie eine neue Datei `group_vars/mgmt.yml` Und Referenzierung des link:custom-architectures-plan-file-system.html["Planen Sie das Dateisystem"^] Geben Sie diesen Abschnitt wie folgt ein:

. Geben Sie diese Datei an, um die Konfiguration für einen BeeGFS-Managementdienst anzuzeigen:
+
[source, yaml]
----
beegfs_service: management
----
. Definieren Sie alle Konfigurationen, die nur für diesen BeeGFS-Dienst gelten sollen. Dies ist in der Regel nicht für den Management-Service erforderlich, es sei denn, Sie müssen Quoten aktivieren, jedoch alle unterstützten Konfigurationsparameter von `beegfs-mgmtd.conf` Kann enthalten sein. Beachten Sie, dass die folgenden Parameter automatisch/an anderer Stelle konfiguriert werden und hier nicht angegeben werden sollten: `storeMgmtdDirectory`, `connAuthFile`, `connDisableAuthentication`, `connInterfacesFile`, und `connNetFilterFile`.
+
[source, yaml]
----
beegfs_ha_beegfs_mgmtd_conf_resource_group_options:
  <beegfs-mgmt.conf:key>:<beegfs-mgmt.conf:value>
----
. Konfigurieren Sie eine oder mehrere unverankerte IPs, die andere Dienste und Clients verwenden, um eine Verbindung zu diesem Dienst herzustellen (dadurch wird das BeeGFS automatisch festgelegt `connInterfacesFile` Option):
+
[source, yaml]
----
floating_ips:
  - <INTERFACE>:<IP/SUBNET> # Primary interface. Ex. i1b:100.127.101.0/16
  - <INTERFACE>:<IP/SUBNET> # Secondary interface(s) as needed.
----
. Geben Sie optional ein oder mehrere zulässige IP-Subnetze an, die für die ausgehende Kommunikation verwendet werden können (dadurch wird automatisch das BeeGFS eingestellt `connNetFilterFile` Option):
+
[source, yaml]
----
filter_ip_ranges:
  - <SUBNET>/<MASK> # Ex. 192.168.10.0/24
----
. Geben Sie das BeeGFS-Managementziel an, auf dem dieser Service Daten gemäß den folgenden Richtlinien speichert:
+
.. Für mehrere BeeGFS Services/Ziele kann derselbe Speicherpool oder Volume-Gruppenname verwendet werden. Stellen Sie einfach sicher, dass er dasselbe verwendet `name`, `raid_level`, `criteria_*`, und `common_*` Konfiguration für jede einzelne (die für jeden Service aufgeführten Volumes sollten unterschiedlich sein).
.. Volume-Größen sollten als Prozentsatz der Storage-Pool/Volume-Gruppe angegeben werden. Die Summe sollte bei allen Services/Volumes, die über einen bestimmten Storage-Pool/Volume-Gruppe verfügen, nicht mehr als 100 übersteigen. Hinweis bei Verwendung von SSDs wird empfohlen, freien Speicherplatz in der Volume-Gruppe zu belassen, um die SSD-Performance und den Verschleiß zu maximieren (klicken Sie auf link:beegfs-deploy-recommended-volume-percentages.html["Hier"^] Entnehmen).
.. Klicken Sie Auf link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["Hier"^] Eine vollständige Liste der für das verfügbaren Konfigurationsoptionen finden Sie unter `eseries_storage_pool_configuration`. Notieren Sie einige Optionen wie z. B. `state`, `host`, `host_type`, `workload_name`, und `workload_metadata` Und Volume-Namen werden automatisch generiert und sollten hier nicht angegeben werden.




[source, yaml]
----
beegfs_targets:
  <BLOCK_NODE>: # The name of the block node as found in the Ansible inventory. Ex: netapp_01
    eseries_storage_pool_configuration:
      - name: <NAME> # Ex: beegfs_m1_m2_m5_m6
        raid_level: <LEVEL> # One of: raid1, raid5, raid6, raidDiskPool
        criteria_drive_count: <DRIVE COUNT> # Ex. 4
        common_volume_configuration:
          segment_size_kb: <SEGMENT SIZE> # Ex. 128
        volumes:
          - size: <PERCENT> # Percent of the pool or volume group to allocate to this volume. Ex. 1
            owning_controller: <CONTROLLER> # One of: A, B
----
Klicken Sie Auf link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/group_vars/mgmt.yml["Hier"^] Beispiel für eine komplette Bestandsdatei, die einen BeeGFS-Managementdienst darstellt.
