---
settings:
  name: BeeGFS on NetApp with E-Series Storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: BeeGFS on NetApp docs
    url: "/index.html"
  - title: Los geht's
    entries:
    - title: Was ist in dieser Site enthalten
      url: "/whats-included.html"
    - title: Begriffe und Konzepte
      url: "/beegfs-terms.html"
    - title: Generationen im Design
      url: "/beegfs-gens.html"
    - title: Lösungsüberblick
      url: "/beegfs-solution-overview.html"
    - title: Überblick über die Architektur
      url: "/beegfs-architecture-overview.html"
    - title: Technische Anforderungen
      url: "/beegfs-technology-requirements.html"
  - title: Überprüfen des Lösungsdesigns
    entries:
    - title: Designübersicht
      url: "/beegfs-design-overview.html"
    - title: Hardwarekonfiguration
      url: "/beegfs-design-hardware-architecture.html"
    - title: Softwarekonfiguration
      url: "/beegfs-design-software-architecture.html"
    - title: Design-Überprüfung
      url: "/beegfs-design-solution-verification.html"
    - title: Richtlinien für die Dimensionierung
      url: "/beegfs-design-solution-sizing-guidelines.html"
    - title: Performance-Optimierung
      url: "/beegfs-design-performance-tuning.html"
  - title: Implementieren der Lösung
    entries:
    - title: Implementierungsübersicht
      url: "/beegfs-deploy-overview.html"
    - title: Weitere Informationen zum Ansible Inventar
      url: "/beegfs-deploy-learn-ansible.html"
    - title: Besprechen der Best Practices
      url: "/beegfs-deploy-bestpractice.html"
    - title: Implementierung von Hardware
      url: "/beegfs-deploy-hardware.html"
    - title: Implementierung von Software
      entries:
      - title: Richten Sie Datei- und Block-Nodes ein
        url: "/beegfs-deploy-setup-nodes.html"
      - title: Passen Sie die Systemeinstellungen für die Performance an
        url: beegfs-deploy-file-node-tuning.html
      - title: Ansible-Steuerungsknoten einrichten
        url: "/beegfs-deploy-setting-up-an-ansible-control-node.html"
      - title: Ansible-Inventar erstellen
        url: "/beegfs-deploy-create-inventory.html"
      - title: Definieren Sie BeeGFS-Bausteine
        url: "/beegfs-deploy-define-inventory.html"
      - title: BeeGFS bereitstellen
        url: "/beegfs-deploy-playbook.html"
      - title: Konfigurieren Sie BeeGFS-Clients
        url: "/beegfs-deploy-configure-clients.html"
    - title: BeeGFS-Cluster skalieren
      url: "/beegfs-deploy-scale-building-blocks.html"
    - title: Empfohlene Volumenprozentwerte
      url: "/beegfs-deploy-recommended-volume-percentages.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
