---
settings:
  name: BeeGFS on NetApp with E-Series Storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: BeeGFS on NetApp docs
    url: "/index.html"
  - title: Los geht's
    entries:
    - title: Was ist in dieser Site enthalten
      url: "/whats-included.html"
    - title: Begriffe und Konzepte
      url: "/beegfs-terms.html"
  - title: Einsatz verifizierter Architekturen
    entries:
    - title: Überblick und Anforderungen
      entries:
      - title: Lösungsüberblick
        url: "/beegfs-solution-overview.html"
      - title: Generationen im Design
        url: "/beegfs-gens.html"
      - title: Überblick über die Architektur
        url: "/beegfs-architecture-overview.html"
      - title: Technische Anforderungen
        url: "/beegfs-technology-requirements.html"
    - title: Überprüfen des Lösungsdesigns
      entries:
      - title: Designübersicht
        url: "/beegfs-design-overview.html"
      - title: Hardwarekonfiguration
        url: "/beegfs-design-hardware-architecture.html"
      - title: Softwarekonfiguration
        url: "/beegfs-design-software-architecture.html"
      - title: Design-Überprüfung
        url: "/beegfs-design-solution-verification.html"
      - title: Richtlinien für die Dimensionierung
        url: "/beegfs-design-solution-sizing-guidelines.html"
      - title: Performance-Optimierung
        url: "/beegfs-design-performance-tuning.html"
      - title: Option mit hoher Kapazität
        url: "/beegfs-design-high-capacity-building-block.html"
    - title: Implementieren der Lösung
      entries:
      - title: Implementierungsübersicht
        url: "/beegfs-deploy-overview.html"
      - title: Weitere Informationen zum Ansible Inventar
        url: "/beegfs-deploy-learn-ansible.html"
      - title: Besprechen der Best Practices
        url: "/beegfs-deploy-bestpractice.html"
      - title: Implementierung von Hardware
        url: "/beegfs-deploy-hardware.html"
      - title: Implementierung von Software
        entries:
        - title: Richten Sie Datei- und Block-Nodes ein
          url: "/beegfs-deploy-setup-nodes.html"
        - title: Passen Sie die Systemeinstellungen für die Performance an
          url: beegfs-deploy-file-node-tuning.html
        - title: Ansible-Steuerungsknoten einrichten
          url: "/beegfs-deploy-setting-up-an-ansible-control-node.html"
        - title: Ansible-Inventar erstellen
          url: "/beegfs-deploy-create-inventory.html"
        - title: Definieren Sie BeeGFS-Bausteine
          url: "/beegfs-deploy-define-inventory.html"
        - title: BeeGFS bereitstellen
          url: "/beegfs-deploy-playbook.html"
        - title: Konfigurieren Sie BeeGFS-Clients
          url: "/beegfs-deploy-configure-clients.html"
      - title: BeeGFS-Cluster skalieren
        url: "/beegfs-deploy-scale-building-blocks.html"
      - title: Empfohlene Volumenprozentwerte
        url: "/beegfs-deploy-recommended-volume-percentages.html"
      - title: Option mit hoher Kapazität
        url: "/beegfs-deploy-high-capacity-building-block.html"
  - title: Verwenden Sie individuelle Architekturen
    entries:
    - title: Überblick und Anforderungen
      url: "/custom-architectures-overview.html"
    - title: Ersteinrichtung
      entries:
      - title: Installieren und verkabeln Sie Hardware
        url: "/custom-architectures-setup-cable-hw.html"
      - title: Richten Sie Datei- und Block-Nodes ein
        url: "/custom-architectures-setup-nodes.html"
      - title: Ansible-Steuerungsknoten einrichten
        url: "/custom-architectures-setup-ansible-control-node.html"
    - title: Definieren Sie das BeeGFS-Dateisystem
      entries:
      - title: Ansible-Bestandsübersicht
        url: "/custom-architectures-inventory-overview.html"
      - title: Planen Sie das Dateisystem
        url: "/custom-architectures-plan-file-system.html"
      - title: Datei- und Blockknoten definieren
        entries:
        - title: Konfigurieren einzelner Datei-Nodes
          url: "/custom-architectures-inventory-configure-file-nodes.html"
        - title: Konfiguration einzelner Block-Nodes
          url: "/custom-architectures-inventory-configure-block-nodes.html"
        - title: Geben Sie die allgemeine Konfiguration des Datei-Nodes an
          url: "/custom-architectures-inventory-common-file-node-configuration.html"
        - title: Geben Sie eine allgemeine Block-Node-Konfiguration an
          url: "/custom-architectures-inventory-common-block-node-configuration.html"
      - title: BeeGFS-Dienste definieren
        entries:
        - title: BeeGFS Management Service
          url: "/custom-architectures-inventory-beegfs-management.html"
        - title: BeeGFS-Metadatendienste
          url: "/custom-architectures-inventory-beegfs-metadata.html"
        - title: BeeGFS Storage-Services
          url: "/custom-architectures-inventory-beegfs-storage.html"
      - title: Zuordnen von BeeGFS-Services zu Datei-Nodes
        url: "/custom-architectures-inventory-map-services-to-file-nodes.html"
    - title: Stellen Sie das BeeGFS-Dateisystem bereit
      entries:
      - title: Ansible – Playbook-Überblick
        url: "/custom-architectures-deploy-playbook-overview.html"
      - title: Implementieren Sie das BeeGFS HA-Cluster
        url: "/custom-architectures-deploy-ha-cluster.html"
      - title: Bereitstellen von BeeGFS-Clients
        url: "/custom-architectures-deploy-beegfs-clients.html"
      - title: Überprüfen Sie die BeeGFS-Bereitstellung
        url: "/custom-architectures-deploy-verify.html"
  - title: BeeGFS-Cluster verwalten
    entries:
    - title: Übersicht, Schlüsselkonzepte und Terminologie
      url: "/administer-clusters-overview.html"
    - title: Verwendung von Ansible und PCs
      url: "/administer-clusters-ansible-pcs.html"
    - title: Untersuchen Sie den Status des Clusters
      url: "/administer-clusters-examine-state.html"
    - title: Neu konfigurieren und aktualisieren
      entries:
      - title: Konfigurieren Sie HA-Cluster und BeeGFS neu
        url: "/administer-clusters-reconfigure.html"
      - title: Aktualisieren Sie den HA-Cluster und BeeGFS
        url: "/administer-clusters-update.html"
    - title: Service und Wartung
      entries:
      - title: Failover- und Failback-Services
        url: "/administer-clusters-failover-failback.html"
      - title: Versetzen Sie das Cluster in den Wartungsmodus
        url: "/administer-clusters-maintenance-mode.html"
      - title: Beenden Sie den Cluster und starten Sie den Cluster
        url: "/administer-clusters-stop-start-cluster.html"
      - title: Datei-Nodes ersetzen
        url: "/administer-clusters-replace-file-nodes.html"
      - title: Erweitern oder verkleinern Sie den Cluster
        url: "/administer-clusters-expand-shrink-cluster.html"
    - title: Fehlerbehebung
      url: "/administer-clusters-troubleshoot.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
