---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Um einen Ansible-Steuerungsknoten einzurichten, identifizieren Sie eine virtuelle oder physische Maschine mit Netzwerkzugriff auf die Verwaltungsports aller Datei- und Block-Nodes, die zum Konfigurieren der Lösung verwendet werden können. 
---
= Richten Sie einen Ansible-Steuerungsknoten ein
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Zum Einrichten eines Ansible-Steuerknotens müssen Sie eine virtuelle oder physische Maschine mit Netzwerkzugriff auf alle Datei- und Block-Nodes zuweisen, die für die BeeGFS auf NetApp Lösung implementiert werden.

Eine Liste der empfohlenen Paketversionen finden Sie imlink:beegfs-technology-requirements.html#ansible-control-node-requirements["Technische Anforderungen"]. Die folgenden Schritte wurden auf Ubuntu 22.04 getestet. Für spezifische Schritte zu Ihrer bevorzugten Linux-Distribution, siehe https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Ansible-Dokumentation"^].

. Installieren Sie über Ihren Ansible Control Node die folgenden Pakete für Python und Python Virtual Environment.
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Erstellen einer virtuellen Python-Umgebung
+
[source, console]
----
python3 -m venv ~/pyenv
----
. Aktivieren Sie die virtuelle Umgebung.
+
[source, console]
----
source ~/pyenv/bin/activate
----
. Installieren Sie die erforderlichen Python-Pakete in der aktivierten virtuellen Umgebung.
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Installieren Sie die BeeGFS-Sammlung mit Ansible Galaxy.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. Überprüfen Sie, ob die installierten Versionen von Ansible, Python und BeeGFS-Sammlung mit der übereinstimmenlink:beegfs-technology-requirements.html#ansible-control-node-requirements["Technische Anforderungen"].
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. Richten Sie passwortloses SSH ein, damit Ansible vom Ansible-Steuerungsknoten aus auf die Remote-BeeGFS-Datei-Nodes zugreifen kann.
+
.. Generieren Sie auf dem Ansible-Steuerungsknoten, falls erforderlich, ein Paar öffentlicher Schlüssel.
+
[source, console]
----
ssh-keygen
----
.. Richten Sie passwortloses SSH für jeden der Dateiknoten ein.
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





IMPORTANT: Richten Sie bei den Blockknoten eine passwortlose SSH ein. Dies wird weder unterstützt noch erforderlich.
