---
sidebar: sidebar 
permalink: second-gen/beegfs-technology-requirements.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Für die Implementierung der BeeGFS auf NetApp Lösung stellen Sie sicher, dass Ihre Umgebung die technologischen Anforderungen erfüllt. 
---
= Technische Anforderungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Stellen Sie zur Implementierung der Lösung BeeGFS auf NetApp sicher, dass Ihre Umgebung die in diesem Dokument beschriebenen Technologieanforderungen erfüllt.



== Anforderungen im Überblick

Diese Seite beschreibt detailliert die Hardware-, Software- und Firmware-Anforderungen für die Implementierung von BeeGFS auf NetApp Bausteinen. Die Anforderungen sind in folgende Abschnitte unterteilt:

* <<Hardwareanforderungen>> - Dateiknoten (Hardware/Software/Firmware), Blockknoten (Hardware/Firmware), Netzwerk und Verkabelung
* <<Anforderungen an die Softwareimplementierung>> - mit Ansible bereitgestellte Komponenten
* <<Ansible-Control-Node-Anforderungen>> - Softwareversionen des Steuerknotens




== Hardwareanforderungen

Bevor Sie beginnen, stellen Sie sicher, dass Ihre Hardware die folgenden Spezifikationen für ein einzelnes Baustein-Design der BeeGFS on NetApp Lösung erfüllt. Die genauen Komponenten für eine bestimmte Implementierung können je nach Kundenanforderungen variieren. Jeder Dateiknoten sollte diese Spezifikationen erfüllen oder übertreffen, um die erwartete Leistung zu erzielen.



=== Anforderungen an Datei-Nodes

[cols="10%,90%"]
|===
| Menge | Spezifikationen 


| 2  a| 
* Lenovo ThinkSystem SR665 V3*

*Hardware:*

* *Prozessoren:* 2x AMD EPYC 9124 16C 3.0 GHz (konfiguriert als zwei NUMA-Zonen)
* *Speicher:* 256 GB (16 x 16 GB TruDDR5 4800 MHz RDIMM-A)
* *PCIe-Erweiterung:* vier PCIe Gen5 x16-Steckplätze (zwei pro NUMA-Zone)
* *HCA-Karten:* 4x MCX755106AS-HEAT ConnectX-7, NDR200, QSFP112, 2-Port, PCIe Gen5 x16, InfiniBand Adapter
* *Speicher:* Zwei Festplatten im RAID 1 für das Betriebssystem (1TB 7.2K SATA oder besser)
* *Verwaltung:* 1GbE-Port für die In-Band-Betriebssystemverwaltung
* *BMC:* 1GbE BMC mit Redfish API für Out-of-Band-Servermanagement
* *Stromversorgung:* Zwei Hot-Swap-Netzteile und Hochleistungslüfter


*Software und Firmware:*

* *Betriebssystem:* Red Hat 9.4 Server Physical mit Hochverfügbarkeit (2 socket)
* *Linux Kernel:* 5.14.0-427.42.1.el9_4.x86_64
* *HCA Firmware:* FW: 28.46.1006, PXE: 3.8.0100, UEFI: 14.39.0013


|===

IMPORTANT: Dateiknoten erfordern ein gültiges Red Hat Enterprise Linux Server-Abonnement und das Red Hat Enterprise Linux High Availability Add-On.



=== Anforderungen an Blockknoten

Jeder Baustein benötigt zwei E-Series-Arrays desselben Modells. Mischen Sie keine Array-Modelle innerhalb desselben Bausteins.

[cols="10%,20%,70%"]
|===
| Menge | Modell | Spezifikationen 


| 2 | EF600  a| 
*Hardware:*

* *Speicher:* 256GB (128GB pro Controller)
* *Adapter:* 2-Port 200Gb/HDR (NVMe/IB)
* *Laufwerke:* Konfiguriert, um die gewünschten Metadaten und die Speicherkapazität zu erfüllen


*Firmware:*

* *SANtricity OS:* 11.90R5
* *NVSRAM:* N6000-890834-D03
* *Laufwerksfirmware:* Neueste verfügbare für Ihre Laufwerksmodelle (siehe link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["E-Series Festplatten-Firmware-Website"^])


|===


=== Anforderungen an Netzwerk-Switches für Speichernetzwerke

[cols="10%,90%"]
|===
| Menge | Spezifikationen 


| 1  a| 
*NVIDIA QM9700 Quantum 2 NDR InfiniBand Switch*

Der Netzwerk-Switch muss InfiniBand-Geschwindigkeiten von 200 Gb/s unterstützen. Der NVIDIA QM9700 ist der empfohlene Switch für den Cluster.

|===

NOTE: Alternative Switches wie der NVIDIA MQM8700 Quantum können verwendet werden, erfordern jedoch eine andere Verkabelung.



=== Verkabelungsanforderungen



==== Blockknoten-zu-Dateiknoten-Kabel

Direkte Verbindungen von Blockknoten zu Dateiknoten erfordern die folgenden Kabel:

[cols="15%,60%,25%"]
|===
| Menge | Kabelspezifikation | Länge 


| 8 | MCP1650-H001E30 - NVIDIA Passives Kupferkabel, QSFP56, 200Gb/s | 1 m 
|===


==== Kabel vom Dateiknoten zum Storage-Switch

Für den NVIDIA QM9700 Quantum 2 Switch werden folgende Kabeltypen empfohlen. Wählen Sie entweder aktive Glasfaser oder passives Kupfer, je nach Ihren Anforderungen. Die Mengenangaben beziehen sich auf jeden Baustein.

[cols="20%,15%,10%,55%"]
|===
| Switch-Modell | Kabeltyp | Menge | Teilenummer 


.4+| NVIDIA QM9700 .3+| Aktive Glasfaser (einschließlich Transceiver) | 2 | MMA4Z00-NS (Multimode, IB/ETH, 800 GB/s 2x400 GB/s Twin-Port OSFP) 


| 4 | MFP7E20-Nxxx (Multimode, 4-Kanal-zu-zwei 2-Kanal-Splitter-Glasfaserkabel) 


| 8 | MMA1Z00-NS400 (Multimode, IB/ETH, 400 GB/s Single-Port QSFP-112) 


| Passives Kupfer | 2 | MCP7Y40-N002 (passives NVIDIA-Kupferverteilerkabel, InfiniBand 800 GB/s bis 4 x 200 GB/s, OSFP auf 4 x QSFP112) 
|===


=== Anforderungen an die Softwareimplementierung

In der folgenden Tabelle sind die automatisch bereitgestellten Softwareanforderungen im Rahmen der Ansible-basierten BeeGFS-Implementierung aufgeführt.

[cols="20%,80%"]
|===
| Software | Version 


| BeeGFS | 8.2.2 


| Corosync | 3.1.8-1 


| Schrittmacher | 2.1.7-5,2 


| Zaunmittel (Rotbarsch/apc) | 4.10.0-62 


| InfiniBand-/RDMA-Treiber | DOCA-OFED-25.04-0.6.1 
|===


=== Ansible-Control-Node-Anforderungen

Die BeeGFS auf NetApp Lösung wird über einen Ansible-Kontroll-Node implementiert und gemanagt. Weitere Informationen finden Sie im https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html["Ansible-Dokumentation"^].

Die in den folgenden Tabellen aufgeführten Software-Anforderungen beziehen sich speziell auf die unten aufgeführte Version der NetApp BeeGFS Ansible Sammlung.

[cols="30%,70%"]
|===
| Software | Version 


| Ansible-Core | >= 2.19.0 


| Python | 3,12 


| Zusätzliche Python-Pakete | Cryptography-46.0.3, netaddr-1.3.0, ipaddr-2.2.0 


| NetApp E-Series BeeGFS Ansible Sammlung | 4.0.0 
|===