---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 'Konfigurieren Sie das Netzwerk auf dem Baseboard Management Controller (BMC) jedes Servers und konfigurieren Sie den Management-Port auf jedem Controller.' 
---
= Einrichten von Datei-Nodes und Block-Nodes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Während die meisten Software-Konfigurationsaufgaben mithilfe der von NetApp zur Verfügung gestellten Ansible Sammlungen automatisiert werden, müssen Sie das Netzwerk auf dem Baseboard Management Controller (BMC) jedes Servers konfigurieren und den Management-Port auf jedem Controller konfigurieren.



== Richten Sie die Datei-Nodes ein

. Konfigurieren Sie das Netzwerk auf dem Baseboard Management Controller (BMC) jedes Servers.
+
Informationen zum Konfigurieren der Netzwerkkonfiguration für die validierten Lenovo SR665 V3-Dateiknoten finden Sie unter https://pubs.lenovo.com/sr665-v3/["Lenovo ThinkSystem Dokumentation"^].

+

NOTE: Ein Baseboard Management Controller (BMC), der manchmal als Service-Prozessor bezeichnet wird, ist der generische Name für die Out-of-Band-Management-Funktion, die in verschiedenen Server-Plattformen integriert ist, die Remote-Zugriff bieten können, selbst wenn das Betriebssystem nicht installiert ist oder nicht zugänglich ist. Anbieter vermarkten diese Funktionalität in der Regel mit ihrem eigenen Branding. Auf dem Lenovo SR665 wird beispielsweise der BMC als _Lenovo XClarity Controller (XCC)_ bezeichnet.

. Konfigurieren Sie die Systemeinstellungen für maximale Performance.
+
Sie konfigurieren die Systemeinstellungen über das UEFI-Setup (früher BIOS) oder über die Redfish APIs, die von vielen BMCs bereitgestellt werden. Die Systemeinstellungen variieren je nach Servermodell, das als Dateiknoten verwendet wird.

+
Informationen zum Konfigurieren der Systemeinstellungen für die validierten Lenovo SR665 V3-Dateiknoten finden Sie unter link:beegfs-deploy-file-node-tuning.html["Passen Sie die Systemeinstellungen für die Performance an"] .

. Installieren Sie Red Hat Enterprise Linux (RHEL) 9.4 und konfigurieren Sie den Hostnamen und den Netzwerkport, die zur Verwaltung des Betriebssystems verwendet werden, einschließlich der SSH-Konnektivität vom Ansible-Steuerknoten.
+
Konfigurieren Sie derzeit keine IPs auf einem der InfiniBand-Ports.

+

NOTE: Die nachfolgenden Abschnitte gehen davon aus, dass die Hostnamen sequenziell nummeriert sind (z. B. h1-HN), und beziehen sich auf Aufgaben, die auf ungeraden oder gar nummerierten Hosts ausgeführt werden sollten.

. Verwenden Sie den Red Hat Subscription Manager, um das System zu registrieren und zu abonnieren, damit die erforderlichen Pakete aus den offiziellen Red Hat-Repositorys installiert werden können und um Updates auf die unterstützte Version von Red Hat zu beschränken:  `subscription-manager release --set=9.4` . Anweisungen hierzu finden Sie unter https://access.redhat.com/solutions/253273["Registrieren und Abonnieren eines RHEL Systems"^] und  https://access.redhat.com/solutions/2761031["Einschränken von Aktualisierungen"^].
. Aktivieren Sie das Red hat Repository mit den für hohe Verfügbarkeit erforderlichen Paketen.
+
....
subscription-manager repo-override --repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
....
. Aktualisieren Sie alle HCA-Firmware auf die in  Verwendung des link:..administer/clusters-update-hca-firmware.html["Aktualisiert die Datei-Node-Adapter-Firmware"^]Handbuchs empfohlene Versionlink:beegfs-technology-requirements.html["Technologieanforderungen erfüllt"].




== Richten Sie Block-Nodes ein

Richten Sie die EF600 Block-Nodes ein, indem Sie den Managementport pro Controller konfigurieren.

. Konfigurieren Sie den Managementport an jedem EF600 Controller.
+
Anweisungen zum Konfigurieren von Ports finden Sie im https://docs.netapp.com/us-en/e-series/install-hw-ef600/complete-setup-task.html#step-2-connect-and-configure-the-management-connection["E-Series Documentation Center"^].

. Legen Sie optional den Speicher-Array-Namen für jedes System fest.
+
Durch das Festlegen eines Namens kann es einfacher sein, in den nachfolgenden Abschnitten auf jedes System zu verweisen. Anweisungen zum Festlegen des Arraynamens finden Sie im https://docs.netapp.com/us-en/e-series-santricity/sm-interface/setup-wizard-overview.html#first-time-setup["E-Series Documentation Center"^].




NOTE: Folgende Themen setzen voraus, dass die Namen der Speicherarrays nacheinander nummeriert sind (z. B. c1 - CN), und beziehen sich auf die Schritte, die auf ungeraden und nicht gerade nummerierten Systemen ausgeführt werden sollten.
