---
sidebar: sidebar 
permalink: administer-clusters-update.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Verwenden Sie Ansible, um BeeGFS und den HA-Cluster zu aktualisieren. 
---
= Aktualisieren Sie den HA-Cluster und BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verwenden Sie Ansible, um BeeGFS und den HA-Cluster zu aktualisieren.



== Überblick

BeeGFS ist nach A versioniert `major.minor.patch` Für jedes unterstützte BeeGFS werden Versioning-Schema und BeeGFS HA Ansible-Rollen bereitgestellt `major.minor` Version (zum Beispiel `beegfs_ha_7_2` Und `beegfs_ha_7_3`). Jede HA-Rolle ist zum Zeitpunkt der Veröffentlichung der Ansible-Sammlung auf die neueste BeeGFS-Patch-Version festgelegt.

Ansible sollte für alle BeeGFS Upgrades verwendet werden, einschließlich dem Verschieben zwischen größeren, kleineren und Patch-Versionen von BeeGFS. Um BeeGFS zu aktualisieren, müssen Sie zuerst die BeeGFS Ansible-Sammlung aktualisieren, die außerdem die neuesten Fixes und Verbesserungen an der Implementierungs-/Management-Automatisierung und dem zugrunde liegenden HA-Cluster heraufgibt. Selbst nach der Aktualisierung auf die neueste Version der Kollektion wird BeeGFS erst aktualisiert `ansible-playbook` Wird mit dem ausgeführt `-e "beegfs_ha_force_upgrade=true"` Einstellen.


NOTE: Weitere Informationen zu BeeGFS-Versionen finden Sie im link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["BeeGFS Upgrade-Dokumentation"^].



== Getestete Upgrade-Pfade

Jede Version der BeeGFS-Kollektion wird mit spezifischen Versionen von BeeGFS getestet, um die Interoperabilität zwischen allen Komponenten zu gewährleisten. Außerdem werden Tests durchgeführt, um sicherzustellen, dass Upgrades von der von der letzten Version der Sammlung unterstützten BeeGFS-Version(en) auf die in der neuesten Version unterstützten durchgeführt werden können.

[cols="1,1,1,5"]
|===
| Originalversion | Upgrade-Version | Multirail | Details 


| 7.2.6 | 7.3.2 | Ja. | Beegfs-Sammlung von v3.0.1 auf v3.1.0, multirail hinzugefügt 


| 7.2.6 | 7.2.8 | Nein | Beegfs-Sammlung wird von v3.0.1 auf v3.1 aktualisiert 


| 7.2.8 | 7.3.1 | Ja. | Upgrade mit beegfs Collection v3.1.0, multirail hinzugefügt 


| 7.3.1 | 7.3.2 | Ja. | Upgrade mit beegfs Collection v3.1.0 
|===


== BeeGFS Upgrade-Schritte

Die folgenden Abschnitte enthalten die Schritte zum Aktualisieren der BeeGFS Ansible-Sammlung und BeeGFS selbst. Achten Sie besonders auf zusätzliche Schritte für die Aktualisierung von BeeGFS Major oder Minor Versionen.



=== Schritt 1: BeeGFS Collection aktualisieren

Bei Erfassungs-Upgrades mit Zugriff auf link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible-Galaxie"^], Ausführen des folgenden Befehls:

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
Laden Sie die Sammlung von herunter, um Offline-Sammlungs-Upgrades von zu erhalten link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible-Galaxie"^] Durch Klicken auf das gewünschte `Install Version`` Und dann `Download tarball`. Übertragen Sie den Tarball auf Ihren Ansible-Steuerungsknoten und führen Sie den folgenden Befehl aus.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
Siehe link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["Sammlungen Werden Installiert"^] Finden Sie weitere Informationen.



=== Schritt: Ansible-Bestandsaufnahme Aktualisieren

Nehmen Sie alle erforderlichen oder gewünschten Aktualisierungen der Ansible-Bestandsdateien Ihres Clusters vor. Siehe link:administer-clusters-update.html#version-upgrade-notes["Hinweise Zum Versionsupgrade"] Im folgenden Abschnitt finden Sie Einzelheiten zu Ihren spezifischen Upgrade-Anforderungen. Siehe link:custom-architectures-overview.html["Verwenden Sie Individuelle Architekturen"^] Abschnitt für allgemeine Informationen zur Konfiguration Ihres BeeGFS HA-Inventars.



=== Schritt 3: Ansible Playbook aktualisieren (nur bei Aktualisierung von Haupt- oder Unterversionen)

Wenn Sie zwischen Major- oder Minor-Versionen wechseln, finden Sie im `playbook.yml` Datei, die zum Bereitstellen und Warten des Clusters verwendet wird, aktualisiert den Namen des `beegfs_ha_<VERSION>` Rolle zur Darstellung der gewünschten Version. Wenn Sie zum Beispiel BeeGFS 7.3 bereitstellen möchten, wäre dies `beegfs_ha_7_3`:

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_3
----
Weitere Informationen zum Inhalt dieser Playbook-Datei finden Sie im link:custom-architectures-deploy-ha-cluster.html["Implementieren Sie das BeeGFS HA-Cluster"^] Abschnitt.



=== Schritt 4: Führen Sie das BeeGFS-Upgrade aus

So wenden Sie das BeeGFS-Update an:

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
Hinter den Kulissen übernimmt die BeeGFS HA-Rolle:

* Stellen Sie sicher, dass sich das Cluster in einem optimalen Zustand befindet, wobei sich jeder BeeGFS-Service auf seinem bevorzugten Node befindet.
* Versetzen Sie das Cluster in den Wartungsmodus.
* Aktualisieren der HA-Cluster-Komponenten (falls erforderlich)
* Aktualisieren Sie jeden Dateiknoten nacheinander wie folgt:
+
** Setzen Sie ihn in den Standby-Modus und führen Sie ein Failover seiner Dienste zum sekundären Knoten durch.
** BeeGFS-Pakete aktualisieren.
** Fallback-Services.


* Verschieben Sie das Cluster aus dem Wartungsmodus.




== Hinweise Zum Versionsupgrade



=== Upgrade von BeeGFS Version 7.2.6 oder 7.3.0



==== Änderungen an der verbindungsbasierten Authentifizierung

BeeGFS-Versionen, die nach 7.3.1 veröffentlicht wurden, erlauben nicht mehr, dass Dienste ohne Angabe von A gestartet werden `connAuthFile` Oder Einstellung `connDisableAuthentication=true` In der Konfigurationsdatei des Dienstes. Es wird dringend empfohlen, die verbindungsbasierte Authentifizierungssicherheit zu aktivieren. Siehe link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["BeeGFS-Verbindungsbasierte Authentifizierung"^] Finden Sie weitere Informationen.

Standardmäßig ist der festgelegt `beegfs_ha*` Rollen generieren und verteilen diese Datei und fügen sie auch zum Ansible-Steuerungsknoten bei hinzu `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`. Der `beegfs_client` Die Rolle überprüft auch, ob diese Datei vorhanden ist, und liefert sie an die Clients, sofern verfügbar.


WARNING: Wenn der `beegfs_client` Die Rolle wurde nicht zur Konfiguration von Clients verwendet. Diese Datei muss manuell auf jeden Client und auf den verteilt werden `connAuthFile` Konfiguration in `beegfs-client.conf` Dateisatz für die Verwendung. Beim Upgrade von einer früheren Version von BeeGFS, bei der die verbindungsbasierte Authentifizierung nicht aktiviert war, verlieren Clients den Zugriff, es sei denn, die auf der Verbindung basierende Authentifizierung ist als Teil des Upgrades durch die Einstellung deaktiviert `beegfs_ha_conn_auth_enabled: false` In `group_vars/ha_cluster.yml` (Nicht empfohlen).

Weitere Details und alternative Konfigurationsoptionen finden Sie im Schritt zur Konfiguration der Verbindungsauthentifizierung im link:custom-architectures-inventory-common-file-node-configuration.html["Festlegen Der Konfiguration Des Gemeinsamen Dateiknotens"^] Abschnitt.
