---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-prereqs.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Voraussetzungen für die Bereitstellung des BeeGFS CSI-Treibers 
---
= Voraussetzungen für die Bereitstellung des BeeGFS CSI-Treibers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bevor Sie den BeeGFS CSI-Treiber bereitstellen und konfigurieren, stellen Sie sicher, dass Sie über einen laufenden Kubernetes-Cluster, Zugriff auf Ihren BeeGFS-Cluster und die entsprechenden Berechtigungen zum Installieren clusterweiter Ressourcen verfügen.



== Überprüfen Sie die Kubernetes-Konfiguration.

Führen Sie den folgenden Befehl aus, um den Status der Pods in Ihrem Kubernetes-Cluster zu überprüfen:

[source, console]
----
kubectl get pods
----
**Erwartete Ausgabe:**

[listing]
----
root@node01:/etc/cni/net.d# kubectl get pods
No resources found in default namespace.
----
Wenn keine Pods ausgeführt werden, ist die Liste leer.  Andernfalls sollten die Pods fehlerfrei aufgelistet werden.



== BeeGFS-Client und -Dienste validieren

Überprüfen Sie mit folgendem Befehl, ob der BeeGFS-Cluster fehlerfrei funktioniert und alle Dienste erreichbar sind:

**BeeGFS 7.4**

[source, console]
----
beegfs-check-servers
----
**BeeGFS 8**

[source, console]
----
beegfs health check
----

NOTE: Der CSI-Treiber funktioniert mit beiden `beegfs-dkms-client` Und `beegfs-client` , das auf jedem Kubernetes-Knoten installiert werden muss.  Die Installationsschritte finden Sie in der BeeGFS Client DKMS-Dokumentation: https://doc.beegfs.io/latest/advanced_topics/client_dkms.html[]

**Erwartete Ausgabe von BeeGFS 7.4:**

[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# beegfs-check-servers
Management
==========
mgmt [ID: 1]: reachable at XXX.X.AB.1:8008 (protocol: TCP)

Metadata
==========
meta_25_tgt_2501 [ID: 2501]: reachable at XXX.X.AA.MN:8255 (protocol: RDMA)
meta_26_tgt_2601 [ID: 2601]: reachable at XXX.X.BB.NO:8265 (protocol: RDMA)
meta_27_tgt_2701 [ID: 2701]: reachable at XXX.X.AA.OP:8275 (protocol: RDMA)
meta_28_tgt_2801 [ID: 2801]: reachable at XXX.X.BB.PQ:8285 (protocol: RDMA)
meta_29_tgt_2901 [ID: 2901]: reachable at XXX.X.AA.QR:8295 (protocol: RDMA)
meta_30_tgt_3001 [ID: 3001]: reachable at XXX.X.BB.RS:8305 (protocol: RDMA)
meta_31_tgt_3101 [ID: 3101]: reachable at XXX.X.AA.ST:8315 (protocol: RDMA)
meta_32_tgt_3201 [ID: 3201]: reachable at XXX.X.BB.TU:8325 (protocol: RDMA)

Storage
==========
stor_25_tgt_2501 [ID: 2501]: reachable at XXX.X.CC.MN:8253 (protocol: RDMA)
stor_26_tgt_2601 [ID: 2601]: reachable at XXX.X.DD.NO:8263 (protocol: RDMA)
stor_27_tgt_2701 [ID: 2701]: reachable at XXX.X.CC.OP:8273 (protocol: RDMA)
stor_28_tgt_2801 [ID: 2801]: reachable at XXX.X.DD.PQ:8283 (protocol: RDMA)
stor_29_tgt_2901 [ID: 2901]: reachable at XXX.X.CC.QR:8293 (protocol: RDMA)
stor_30_tgt_3001 [ID: 3001]: reachable at XXX.X.DD.RS:8303 (protocol: RDMA)
stor_31_tgt_3101 [ID: 3101]: reachable at XXX.X.CC.ST:8313 (protocol: RDMA)
stor_32_tgt_3201 [ID: 3201]: reachable at XXX.X.DD.32:8323 (protocol: RDMA)
----
Falls einzelne Dienste nicht erreichbar sind, stellen Sie sicher, dass der BeeGFS-Client korrekt konfiguriert ist und die Netzwerkverbindung zu den BeeGFS-Servern funktioniert.
