---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-verify.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Überprüfung der BeeGFS CSI-Treiberbereitstellung. 
---
= Überprüfung der BeeGFS CSI-Treiberbereitstellung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um zu überprüfen, ob der BeeGFS CSI-Treiber erfolgreich bereitgestellt wurde, überprüfen Sie den Status der CSI-Treiber-Pods und vergewissern Sie sich, dass sie wie erwartet laufen.

Um den Status aller Ressourcen im BeeGFS-CSI-Namensraum zu überprüfen, führen Sie folgenden Befehl aus:

[source, console]
----
kubectl get all -n beegfs-csi
----
**Erwartete Ausgabe:**

[listing]
----
NAME                          READY    STATUS      RESTARTS    AGE
pod/csi-beegfs-controller-0   3/3      Running     0           5d11h
pod/csi-beegfs-node-8f917     3/3      Running     0           5d11h
----


== Controller-Pod prüfen

Um Probleme zu diagnostizieren oder weitere Details zum BeeGFS CSI Controller-Pod zu erhalten, verwenden Sie den folgenden Befehl, um den Pod zu beschreiben und seine Ereignisse, seinen Status und seine letzten Aktivitäten zu überprüfen:

[source, console]
----
kubectl describe pod csi-beegfs-controller-0 -n beegfs-csi
----
**Erwartete Ausgabe:**

[listing]
----
Events:

  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  117s                 default-scheduler  Successfully assigned beegfs-csi/csi-beegfs-controller-0 to node01
  Normal   Pulled     117s                 kubelet            Container image "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0" already present on machine
  Normal   Created    117s                 kubelet            Created container: csi-provisioner
  Normal   Started    117s                 kubelet            Started container csi-provisioner
  Normal   Started    101s (x3 over 117s)  kubelet            Started container beegfs
  Normal   Pulled     86s (x2 over 117s)   kubelet            Container image "registry.k8s.io/sig-storage/csi-resizer:v1.11.1" already present on machine
  Normal   Created    86s (x2 over 117s)   kubelet            Created container: csi-resizer
  Normal   Started    86s (x2 over 117s)   kubelet            Started container csi-resizer
  Warning  BackOff    85s (x5 over 115s)   kubelet            Back-off restarting failed container beegfs in pod csi-beegfs-controller-0_beegfs-csi(47016fd3-3a2a-41ed-bc4c-5a716c377b1e)
  Normal   Pulled     73s (x4 over 117s)   kubelet            Container image "ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0" already present on machine
  Normal   Created    73s (x4 over 117s)   kubelet            Created container: beegfs
----


== Speicherklasse überprüfen

. Überprüfen Sie, ob die StorageClass erfolgreich erstellt wurde:
+
[source, console]
----
kubectl get sc
----
+
**Erwartete Ausgabe:**

+
[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl get sc
NAME                PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-beegfs-dyn-sc   beegfs.csi.org.com   Delete          Immediate           true                   17s
----
. Vergewissern Sie sich, dass das BeeGFS-Volume wie erwartet eingebunden ist.
+
Überprüfen Sie das angegebene Verzeichnis als `volDirBasePath` In `examples/k8s/dyn/dyn-sc.yaml` erscheint unter `/mnt/beegfs` Die

+
Wenn `volDirBasePath` ist eingestellt auf `user_id_k8s` Sie sollten dieses Verzeichnis in der Liste sehen:

+
[source, console]
----
root@node01:/# ls -ltr /mnt/beegfs/
total 1
drwxrwxrwx 4 root root 2 Oct 15 10:16 user_id_k8s
----

