---
sidebar: sidebar 
permalink: administer-clusters-maintenance-mode.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, maintenance 
summary: Verhindern Sie, dass das HA-Cluster versehentlich auf geplante Änderungen in der Umgebung reagiert. 
---
= Versetzen Sie das Cluster in den Wartungsmodus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verhindern Sie, dass das HA-Cluster versehentlich auf geplante Änderungen in der Umgebung reagiert.



== Überblick

Wenn Sie das Cluster in den Wartungsmodus versetzen, werden die gesamte Ressourcenüberwachung deaktiviert und Pacemaker kann nicht mehr Ressourcen im Cluster verschieben oder anderweitig verwalten. Alle Ressourcen werden auf den ursprünglichen Nodes weiterhin ausgeführt, unabhängig davon, ob es eine temporäre Ausfallbedingung gibt, die den Zugriff auf sie verhindern würde. Dies wird empfohlen/ist u. a.:

* Netzwerkwartung, die vorübergehend Verbindungen zwischen Datei-Nodes und BeeGFS-Diensten unterbrechen kann.
* Block-Node-Upgrades:
* Dateiknoten-Betriebssystem, Kernel oder andere Paketaktualisierungen.


Im Allgemeinen ist der einzige Grund, das Cluster manuell in den Wartungsmodus zu versetzen, um zu verhindern, dass es auf externe Änderungen in der Umgebung reagiert. Wenn für einen einzelnen Node im Cluster die physische Reparatur erforderlich ist, verwenden Sie keinen Wartungsmodus und platzieren Sie den Node einfach gemäß dem oben beschriebenen Verfahren in Standby. Beachten Sie, dass bei der Umleitung von Ansible der Cluster automatisch der Wartungsmodus für die meisten Softwarewartungsarbeiten einschließlich Upgrades und Konfigurationsänderungen durchgeführt wird.



== Schritte

So überprüfen Sie, ob das Cluster sich im Wartungsmodus befindet:

[source, console]
----
pcs property show maintenance-mode
----
Dies gibt FALSE zurück, wenn das Cluster ordnungsgemäß ausgeführt wird. Um den Wartungsmodus zu aktivieren, führen Sie folgende Schritte aus:

[source, console]
----
pcs property set maintenance-mode=true
----
Sie können überprüfen, indem Sie den PC-Status ausführen und sicherstellen, dass alle Ressourcen „(nicht verwaltet)“ anzeigen. Um das Cluster aus dem Wartungsmodus zu nehmen, führen Sie folgende Schritte aus:

[source, console]
----
pcs property set maintenance-mode=false
----