---
sidebar: sidebar 
permalink: administer/clusters-ansible-pcs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs, Ansible 
summary: Wann sollten Sie Ansible im Vergleich zum PCs-Befehlszeilungstool für das Management des HA-Clusters verwenden? 
---
= Wann Ansible im Vergleich zum Tool PCs verwendet werden soll
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wann sollten Sie Ansible im Vergleich zum PCs-Befehlszeilungstool für das Management des HA-Clusters verwenden?

Alle Cluster-Implementierungs- und Neukonfigurierungsaufgaben sollten mit Ansible von einem externen Ansible-Kontroll-Node abgeschlossen werden. Temporäre Änderungen im Clusterstatus (z. B. ein- und Ausstellen von Knoten in den Standby-Modus) werden in der Regel durch Anmeldung an einem Knoten des Clusters (vorzugsweise einer, der nicht beeinträchtigt ist oder sich über die Wartung befindet) und unter Verwendung des Befehlszeilen-Tools PCs durchgeführt.

Das Ändern einer beliebigen Cluster-Konfiguration einschließlich Ressourcen, Einschränkungen, Eigenschaften und der BeeGFS Services selbst sollte immer mit Ansible erfolgen. Das Verwalten einer aktuellen Kopie des Ansible-Bestands und Playbook (ideal zur Versionskontrolle, um Änderungen zu verfolgen) ist Teil der Wartung des Clusters. Wenn Sie Änderungen an der Konfiguration vornehmen müssen, aktualisieren Sie den Bestand und führen Sie das Ansible-Playbook aus, das die BeeGFS HA-Rolle importiert.

Die HA-Rolle verarbeitet, das Cluster in den Wartungsmodus zu platzieren und anschließend alle erforderlichen Änderungen vorzunehmen, bevor BeeGFS oder Cluster-Services neu gestartet werden, um die neue Konfiguration anzuwenden. Da in der Regel keine vollständigen Node-Neustarts außerhalb der ursprünglichen Implementierung erforderlich sind, wird das Rerunning von Ansible in der Regel als „sicheres“ Verfahren angesehen. Für den Fall, dass BeeGFS-Services neu gestartet werden müssen, wird jedoch immer während Wartungsfenster oder außerhalb der Geschäftszeiten empfohlen. Diese Neustarts sollten in der Regel keine Anwendungsfehler verursachen, können aber die Leistung beeinträchtigen (was einige Anwendungen besser verarbeiten können als andere).

Die erneute Ausführung von Ansible ist auch eine Option, wenn Sie den gesamten Cluster wieder in einen vollkommen optimalen Zustand zurückversetzen möchten, und kann in einigen Fällen den Status des Clusters einfacher wiederherstellen als PCs. Insbesondere in einem Notfall, in dem der Cluster aus irgendeinem Grund ausgefallen ist, kann, wenn alle Knoten gesichert werden, Ansible neu zu starten, den Cluster schneller und zuverlässiger wiederherstellen, als zu versuchen, PCs zu verwenden.
