---
sidebar: sidebar 
permalink: custom-architectures-deploy-verify.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Überprüfen Sie die Bereitstellung des Dateisystems, bevor Sie das System in die Produktion bringen. 
---
= Überprüfen Sie die BeeGFS-Bereitstellung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Überprüfen Sie die Bereitstellung des Dateisystems, bevor Sie das System in die Produktion bringen.



== Überblick

Bevor Sie das BeeGFS-Dateisystem in Produktion setzen, führen Sie einige Überprüfungsprüfungen durch.



=== Schritte

. Melden Sie sich bei einem Client an und führen Sie Folgendes aus, um sicherzustellen, dass alle erwarteten Knoten vorhanden/erreichbar sind, und es werden keine Inkonsistenzen oder andere Probleme gemeldet:
+
[source, bash]
----
beegfs-fsck --checkfs
----
. Fahren Sie den gesamten Cluster herunter und starten Sie ihn dann neu. Führen Sie von jedem beliebigen Dateiknoten Folgendes aus:
+
[source, bash]
----
pcs cluster stop --all # Stop the cluster on all file nodes.
pcs cluster start --all  # Start the cluster on all file nodes.
pcs status # Verify all nodes and services are started and no failures are reported (the command may need to be reran a few times to allow time for all services to start).
----
. Platzieren Sie jeden Knoten in den Standby-Modus, und überprüfen Sie, ob BeeGFS-Dienste einen Failover auf sekundäre Knoten ausführen können. So melden Sie sich an einem beliebigen Dateiknoten an und führen Sie Folgendes aus:
+
[source, bash]
----
pcs status # Verify the cluster is healthy at the start.
pcs node standby <FILE NODE HOSTNAME> # Place the node under test in standby.
pcs status # Verify services are started on a secondary node and no failures are reported.
pcs node unstandby <FILE NODE HOSTNAME> # Take the node under test out of standby.
pcs status # Verify the file node is back online and no failures are reported.
pcs resource relocate run # Move all services back to their preferred nodes.
pcs status # Verify services have moved back to the preferred node.
----
. Verwenden Sie Tools zum Leistungsvergleich wie IOR und MDTest, um zu überprüfen, ob die Performance des Dateisystems den Erwartungen entspricht. Beispiele für häufige Tests und Parameter, die mit BeeGFS verwendet werden, finden Sie im link:/beegfs-design-solution-verification.html["Design-Verifizierung"^] Abschnitt des BeeGFS auf NetApp Verified Architecture.


Zusätzliche Tests sollten auf Grundlage der Abnahmekriterien durchgeführt werden, die für einen bestimmten Standort/eine bestimmte Installation definiert sind.
