---
sidebar: sidebar 
permalink: get-started/whats-included.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Auf dieser Website wird dokumentiert, wie BeeGFS auf NetApp bereitgestellt und gemanagt wird. 
---
= Was ist in dieser Website enthalten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Auf dieser Website wird dokumentiert, wie BeeGFS auf NetApp mit sowohl NetApp Verified Architectures (NVAs) als auch individuellen Architekturen implementiert und gemanagt wird. NVA-Designs werden ausführlich getestet und bieten Kunden Referenzkonfigurationen und Anleitungen zur Größenbestimmung, um Implementierungsrisiken zu minimieren und die Markteinführungszeit zu beschleunigen. NetApp unterstützt außerdem individuelle BeeGFS-Architekturen, die auf NetApp Hardware ausgeführt werden. So können Kunden und Partner flexibel Filesysteme entwerfen, die einen breiten Anforderungsspektrum erfüllen. Beide Ansätze nutzen Ansible für die Implementierung und bieten einen Appliance-ähnlichen Ansatz, mit dem BeeGFS in jeder Größenordnung über ein flexibles Spektrum an Hardware gemanagt werden kann.
